# Generated by Django 5.1.6 on 2025-03-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(related_name='artists', to='music.genre'),
        ),
        migrations.AddField(
            model_name='artistalbum',
            name='genres',
            field=models.ManyToManyField(related_name='albums', to='music.genre'),
        ),
        migrations.AddField(
            model_name='platformmix',
            name='genres',
            field=models.ManyToManyField(related_name='mixes', to='music.genre'),
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(related_name='songs', to='music.genre'),
        ),
    ]
