# Generated by Django 5.1.6 on 2025-03-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_genre_artist_genres_artistalbum_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artists', to='music.genre'),
        ),
        migrations.AlterField(
            model_name='artistalbum',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='albums', to='music.genre'),
        ),
        migrations.AlterField(
            model_name='platformmix',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='mixes', to='music.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.genre'),
        ),
    ]
