# Generated by Django 5.1.6 on 2025-03-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_artist_genres_alter_artistalbum_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songcollection',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
