# Generated by Django 5.1.6 on 2025-03-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_artist_image_url_song_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
