# Generated by Django 5.1.6 on 2025-03-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_artist_slug_alter_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default='change-me', max_length=150),
            preserve_default=False,
        ),
    ]
