# Generated by Django 5.1.6 on 2025-03-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
