# Generated by Django 5.1.6 on 2025-03-24 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_rename_image_url_artist_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistalbum',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist'),
        ),
    ]
