# Generated by Django 5.1.6 on 2025-04-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_artistalbum_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
