# Generated by Django 5.1.6 on 2025-04-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_artist_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
