# Generated by Django 5.1.6 on 2025-04-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_artist_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistalbum',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
