# Generated by Django 5.1.6 on 2025-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_alter_artistalbum_spotify_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_url',
            field=models.URLField(max_length=500),
        ),
    ]
