# Generated by Django 5.1.6 on 2025-04-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_remove_song_artist_song_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmix',
            name='spotify_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
